site_name: Tangerine Documentation
repo_url: https://github.com/Tangerine-Community/TestingDocumentation2
site_author: Tangerine Community
theme:
  name: material
  language: en
  features:
    - tabs
  logo: assets/tangerine-logo.svg
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  - minify:
      minify_html: true
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
